namespace Zot2Bib;

public class ZotItem
{
    public int ItemId { get; set; }
    public string? Title { get; set; }
    public string? AbstractNote { get; set; }
    public string? ArtworkMedium { get; set; }
    public string? Medium { get; set; }
    public string? ArtworkSize { get; set; }
    public string? Date { get; set; }
    public string? Language { get; set; }
    public string? ShortTitle { get; set; }
    public string? Archive { get; set; }
    public string? ArchiveLocation { get; set; }
    public string? LibraryCatalog { get; set; }
    public string? CallNumber { get; set; }
    public string? Url { get; set; }
    public string? AccessDate { get; set; }
    public string? Rights { get; set; }
    public string? Extra { get; set; }
    public string? AudioRecordingFormat { get; set; }
    public string? SeriesTitle { get; set; }
    public string? Volume { get; set; }
    public string? NumberOfVolumes { get; set; }
    public string? Place { get; set; }
    public string? Label { get; set; }
    public string? Publisher { get; set; }
    public string? RunningTime { get; set; }
    public string? Isbn { get; set; }
    public string? BillNumber { get; set; }
    public string? Number { get; set; }
    public string? Code { get; set; }
    public string? CodeVolume { get; set; }
    public string? Section { get; set; }
    public string? CodePages { get; set; }
    public string? Pages { get; set; }
    public string? LegislativeBody { get; set; }
    public string? Authority { get; set; }
    public string? Session { get; set; }
    public string? History { get; set; }
    public string? BlogTitle { get; set; }
    public string? PublicationTitle { get; set; }
    public string? WebsiteType { get; set; }
    public string? Type { get; set; }
    public string? Series { get; set; }
    public string? SeriesNumber { get; set; }
    public string? Edition { get; set; }
    public string? NumPages { get; set; }
    public string? BookTitle { get; set; }
    public string? CaseName { get; set; }
    public string? Court { get; set; }
    public string? DateDecided { get; set; }
    public string? DocketNumber { get; set; }
    public string? Reporter { get; set; }
    public string? ReporterVolume { get; set; }
    public string? FirstPage { get; set; }
    public string? VersionNumber { get; set; }
    public string? System { get; set; }
    public string? Company { get; set; }
    public string? ProgrammingLanguage { get; set; }
    public string? ProceedingsTitle { get; set; }
    public string? ConferenceName { get; set; }
    public string? Doi { get; set; }
    public string? Identifier { get; set; }
    public string? Repository { get; set; }
    public string? RepositoryLocation { get; set; }
    public string? Format { get; set; }
    public string? CitationKey { get; set; }
    public string? DictionaryTitle { get; set; }
    public string? Subject { get; set; }
    public string? EncyclopediaTitle { get; set; }
    public string? Distributor { get; set; }
    public string? Genre { get; set; }
    public string? VideoRecordingFormat { get; set; }
    public string? ForumTitle { get; set; }
    public string? PostType { get; set; }
    public string? Committee { get; set; }
    public string? DocumentNumber { get; set; }
    public string? InterviewMedium { get; set; }
    public string? Issue { get; set; }
    public string? SeriesText { get; set; }
    public string? JournalAbbreviation { get; set; }
    public string? Issn { get; set; }
    public string? LetterType { get; set; }
    public string? ManuscriptType { get; set; }
    public string? MapType { get; set; }
    public string? Scale { get; set; }
    public string? Country { get; set; }
    public string? Assignee { get; set; }
    public string? IssuingAuthority { get; set; }
    public string? PatentNumber { get; set; }
    public string? FilingDate { get; set; }
    public string? ApplicationNumber { get; set; }
    public string? PriorityNumbers { get; set; }
    public string? IssueDate { get; set; }
    public string? References { get; set; }
    public string? LegalStatus { get; set; }
    public string? Status { get; set; }
    public string? EpisodeNumber { get; set; }
    public string? AudioFileType { get; set; }
    public string? ArchiveId { get; set; }
    public string? PresentationType { get; set; }
    public string? MeetingName { get; set; }
    public string? ProgramTitle { get; set; }
    public string? Network { get; set; }
    public string? ReportNumber { get; set; }
    public string? ReportType { get; set; }
    public string? Institution { get; set; }
    public string? Organization { get; set; }
    public string? NameOfAct { get; set; }
    public string? CodeNumber { get; set; }
    public string? PublicLawNumber { get; set; }
    public string? DateEnacted { get; set; }
    public string? ThesisType { get; set; }
    public string? University { get; set; }
    public string? Studio { get; set; }
    public string? WebsiteTitle { get; set; }
}
