-- itemID -> 2270

DROP VIEW IF EXISTS mainTable;
CREATE TEMPORARY VIEW IF NOT EXISTS mainTable (
  itemID, 'title', 'abstractNote', 'artworkMedium', 'medium', 'artworkSize', 'date', 'language', 'shortTitle', 'archive', 'archiveLocation', 'libraryCatalog', 'callNumber', 'url', 'accessDate', 'rights', 'extra', 'audioRecordingFormat', 'seriesTitle', 'volume', 'numberOfVolumes', 'place', 'label', 'publisher', 'runningTime', ISBN, 'billNumber', 'number', 'code', 'codeVolume', 'section', 'codePages', 'pages', 'legislativeBody', 'authority', 'session', 'history', 'blogTitle', 'publicationTitle', 'websiteType', 'type', 'series', 'seriesNumber', 'edition', 'numPages', 'bookTitle', 'caseName', 'court', 'dateDecided', 'docketNumber', 'reporter', 'reporterVolume', 'firstPage', 'versionNumber', 'system', 'company', 'programmingLanguage', 'proceedingsTitle', 'conferenceName', DOI, 'identifier', 'repository', 'repositoryLocation', 'format', 'citationKey', 'dictionaryTitle', 'subject', 'encyclopediaTitle', 'distributor', 'genre', 'videoRecordingFormat', 'forumTitle', 'postType', 'committee', 'documentNumber', 'interviewMedium', 'issue', 'seriesText', 'journalAbbreviation', ISSN, 'letterType', 'manuscriptType', 'mapType', 'scale', 'country', 'assignee', 'issuingAuthority', 'patentNumber', 'filingDate', 'applicationNumber', 'priorityNumbers', 'issueDate', 'references', 'legalStatus', 'status', 'episodeNumber', 'audioFileType', 'archiveID', 'presentationType', 'meetingName', 'programTitle', 'network', 'reportNumber', 'reportType', 'institution', 'organization', 'nameOfAct', 'codeNumber', 'publicLawNumber', 'dateEnacted', 'thesisType', 'university', 'studio', 'websiteTitle'
) AS SELECT
  items.itemID,
  group_concat(CASE WHEN fieldname = 'title' THEN itemdatavalues.value END) AS 'title',
  group_concat(CASE WHEN fieldname = 'abstractNote' THEN itemdatavalues.value END) AS 'abstractNote',
  group_concat(CASE WHEN fieldname = 'artworkMedium' THEN itemdatavalues.value END) AS 'artworkMedium',
  group_concat(CASE WHEN fieldname = 'medium' THEN itemdatavalues.value END) AS 'medium',
  group_concat(CASE WHEN fieldname = 'artworkSize' THEN itemdatavalues.value END) AS 'artworkSize',
  group_concat(CASE WHEN fieldname = 'date' THEN itemdatavalues.value END) AS 'date',
  group_concat(CASE WHEN fieldname = 'language' THEN itemdatavalues.value END) AS 'language',
  group_concat(CASE WHEN fieldname = 'shortTitle' THEN itemdatavalues.value END) AS 'shortTitle',
  group_concat(CASE WHEN fieldname = 'archive' THEN itemdatavalues.value END) AS 'archive',
  group_concat(CASE WHEN fieldname = 'archiveLocation' THEN itemdatavalues.value END) AS 'archiveLocation',
  group_concat(CASE WHEN fieldname = 'libraryCatalog' THEN itemdatavalues.value END) AS 'libraryCatalog',
  group_concat(CASE WHEN fieldname = 'callNumber' THEN itemdatavalues.value END) AS 'callNumber',
  group_concat(CASE WHEN fieldname = 'url' THEN itemdatavalues.value END) AS 'url',
  group_concat(CASE WHEN fieldname = 'accessDate' THEN itemdatavalues.value END) AS 'accessDate',
  group_concat(CASE WHEN fieldname = 'rights' THEN itemdatavalues.value END) AS 'rights',
  group_concat(CASE WHEN fieldname = 'extra' THEN itemdatavalues.value END) AS 'extra',
  group_concat(CASE WHEN fieldname = 'audioRecordingFormat' THEN itemdatavalues.value END) AS 'audioRecordingFormat',
  group_concat(CASE WHEN fieldname = 'seriesTitle' THEN itemdatavalues.value END) AS 'seriesTitle',
  group_concat(CASE WHEN fieldname = 'volume' THEN itemdatavalues.value END) AS 'volume',
  group_concat(CASE WHEN fieldname = 'numberOfVolumes' THEN itemdatavalues.value END) AS 'numberOfVolumes',
  group_concat(CASE WHEN fieldname = 'place' THEN itemdatavalues.value END) AS 'place',
  group_concat(CASE WHEN fieldname = 'label' THEN itemdatavalues.value END) AS 'label',
  group_concat(CASE WHEN fieldname = 'publisher' THEN itemdatavalues.value END) AS 'publisher',
  group_concat(CASE WHEN fieldname = 'runningTime' THEN itemdatavalues.value END) AS 'runningTime',
  group_concat(CASE WHEN fieldname = 'ISBN' THEN itemdatavalues.value END) AS ISBN,
  group_concat(CASE WHEN fieldname = 'billNumber' THEN itemdatavalues.value END) AS 'billNumber',
  group_concat(CASE WHEN fieldname = 'number' THEN itemdatavalues.value END) AS 'number',
  group_concat(CASE WHEN fieldname = 'code' THEN itemdatavalues.value END) AS 'code',
  group_concat(CASE WHEN fieldname = 'codeVolume' THEN itemdatavalues.value END) AS 'codeVolume',
  group_concat(CASE WHEN fieldname = 'section' THEN itemdatavalues.value END) AS 'section',
  group_concat(CASE WHEN fieldname = 'codePages' THEN itemdatavalues.value END) AS 'codePages',
  group_concat(CASE WHEN fieldname = 'pages' THEN itemdatavalues.value END) AS 'pages',
  group_concat(CASE WHEN fieldname = 'legislativeBody' THEN itemdatavalues.value END) AS 'legislativeBody',
  group_concat(CASE WHEN fieldname = 'authority' THEN itemdatavalues.value END) AS 'authority',
  group_concat(CASE WHEN fieldname = 'session' THEN itemdatavalues.value END) AS 'session',
  group_concat(CASE WHEN fieldname = 'history' THEN itemdatavalues.value END) AS 'history',
  group_concat(CASE WHEN fieldname = 'blogTitle' THEN itemdatavalues.value END) AS 'blogTitle',
  group_concat(CASE WHEN fieldname = 'publicationTitle' THEN itemdatavalues.value END) AS 'publicationTitle',
  group_concat(CASE WHEN fieldname = 'websiteType' THEN itemdatavalues.value END) AS 'websiteType',
  group_concat(CASE WHEN fieldname = 'type' THEN itemdatavalues.value END) AS 'type',
  group_concat(CASE WHEN fieldname = 'series' THEN itemdatavalues.value END) AS 'series',
  group_concat(CASE WHEN fieldname = 'seriesNumber' THEN itemdatavalues.value END) AS 'seriesNumber',
  group_concat(CASE WHEN fieldname = 'edition' THEN itemdatavalues.value END) AS 'edition',
  group_concat(CASE WHEN fieldname = 'numPages' THEN itemdatavalues.value END) AS 'numPages',
  group_concat(CASE WHEN fieldname = 'bookTitle' THEN itemdatavalues.value END) AS 'bookTitle',
  group_concat(CASE WHEN fieldname = 'caseName' THEN itemdatavalues.value END) AS 'caseName',
  group_concat(CASE WHEN fieldname = 'court' THEN itemdatavalues.value END) AS 'court',
  group_concat(CASE WHEN fieldname = 'dateDecided' THEN itemdatavalues.value END) AS 'dateDecided',
  group_concat(CASE WHEN fieldname = 'docketNumber' THEN itemdatavalues.value END) AS 'docketNumber',
  group_concat(CASE WHEN fieldname = 'reporter' THEN itemdatavalues.value END) AS 'reporter',
  group_concat(CASE WHEN fieldname = 'reporterVolume' THEN itemdatavalues.value END) AS 'reporterVolume',
  group_concat(CASE WHEN fieldname = 'firstPage' THEN itemdatavalues.value END) AS 'firstPage',
  group_concat(CASE WHEN fieldname = 'versionNumber' THEN itemdatavalues.value END) AS 'versionNumber',
  group_concat(CASE WHEN fieldname = 'system' THEN itemdatavalues.value END) AS 'system',
  group_concat(CASE WHEN fieldname = 'company' THEN itemdatavalues.value END) AS 'company',
  group_concat(CASE WHEN fieldname = 'programmingLanguage' THEN itemdatavalues.value END) AS 'programmingLanguage',
  group_concat(CASE WHEN fieldname = 'proceedingsTitle' THEN itemdatavalues.value END) AS 'proceedingsTitle',
  group_concat(CASE WHEN fieldname = 'conferenceName' THEN itemdatavalues.value END) AS 'conferenceName',
  group_concat(CASE WHEN fieldname = 'DOI' THEN itemdatavalues.value END) AS DOI,
  group_concat(CASE WHEN fieldname = 'identifier' THEN itemdatavalues.value END) AS 'identifier',
  group_concat(CASE WHEN fieldname = 'repository' THEN itemdatavalues.value END) AS 'repository',
  group_concat(CASE WHEN fieldname = 'repositoryLocation' THEN itemdatavalues.value END) AS 'repositoryLocation',
  group_concat(CASE WHEN fieldname = 'format' THEN itemdatavalues.value END) AS 'format',
  group_concat(CASE WHEN fieldname = 'citationKey' THEN itemdatavalues.value END) AS 'citationKey',
  group_concat(CASE WHEN fieldname = 'dictionaryTitle' THEN itemdatavalues.value END) AS 'dictionaryTitle',
  group_concat(CASE WHEN fieldname = 'subject' THEN itemdatavalues.value END) AS 'subject',
  group_concat(CASE WHEN fieldname = 'encyclopediaTitle' THEN itemdatavalues.value END) AS 'encyclopediaTitle',
  group_concat(CASE WHEN fieldname = 'distributor' THEN itemdatavalues.value END) AS 'distributor',
  group_concat(CASE WHEN fieldname = 'genre' THEN itemdatavalues.value END) AS 'genre',
  group_concat(CASE WHEN fieldname = 'videoRecordingFormat' THEN itemdatavalues.value END) AS 'videoRecordingFormat',
  group_concat(CASE WHEN fieldname = 'forumTitle' THEN itemdatavalues.value END) AS 'forumTitle',
  group_concat(CASE WHEN fieldname = 'postType' THEN itemdatavalues.value END) AS 'postType',
  group_concat(CASE WHEN fieldname = 'committee' THEN itemdatavalues.value END) AS 'committee',
  group_concat(CASE WHEN fieldname = 'documentNumber' THEN itemdatavalues.value END) AS 'documentNumber',
  group_concat(CASE WHEN fieldname = 'interviewMedium' THEN itemdatavalues.value END) AS 'interviewMedium',
  group_concat(CASE WHEN fieldname = 'issue' THEN itemdatavalues.value END) AS 'issue',
  group_concat(CASE WHEN fieldname = 'seriesText' THEN itemdatavalues.value END) AS 'seriesText',
  group_concat(CASE WHEN fieldname = 'journalAbbreviation' THEN itemdatavalues.value END) AS 'journalAbbreviation',
  group_concat(CASE WHEN fieldname = 'ISSN' THEN itemdatavalues.value END) AS ISSN,
  group_concat(CASE WHEN fieldname = 'letterType' THEN itemdatavalues.value END) AS 'letterType',
  group_concat(CASE WHEN fieldname = 'manuscriptType' THEN itemdatavalues.value END) AS 'manuscriptType',
  group_concat(CASE WHEN fieldname = 'mapType' THEN itemdatavalues.value END) AS 'mapType',
  group_concat(CASE WHEN fieldname = 'scale' THEN itemdatavalues.value END) AS 'scale',
  group_concat(CASE WHEN fieldname = 'country' THEN itemdatavalues.value END) AS 'country',
  group_concat(CASE WHEN fieldname = 'assignee' THEN itemdatavalues.value END) AS 'assignee',
  group_concat(CASE WHEN fieldname = 'issuingAuthority' THEN itemdatavalues.value END) AS 'issuingAuthority',
  group_concat(CASE WHEN fieldname = 'patentNumber' THEN itemdatavalues.value END) AS 'patentNumber',
  group_concat(CASE WHEN fieldname = 'filingDate' THEN itemdatavalues.value END) AS 'filingDate',
  group_concat(CASE WHEN fieldname = 'applicationNumber' THEN itemdatavalues.value END) AS 'applicationNumber',
  group_concat(CASE WHEN fieldname = 'priorityNumbers' THEN itemdatavalues.value END) AS 'priorityNumbers',
  group_concat(CASE WHEN fieldname = 'issueDate' THEN itemdatavalues.value END) AS 'issueDate',
  group_concat(CASE WHEN fieldname = 'references' THEN itemdatavalues.value END) AS 'references',
  group_concat(CASE WHEN fieldname = 'legalStatus' THEN itemdatavalues.value END) AS 'legalStatus',
  group_concat(CASE WHEN fieldname = 'status' THEN itemdatavalues.value END) AS 'status',
  group_concat(CASE WHEN fieldname = 'episodeNumber' THEN itemdatavalues.value END) AS 'episodeNumber',
  group_concat(CASE WHEN fieldname = 'audioFileType' THEN itemdatavalues.value END) AS 'audioFileType',
  group_concat(CASE WHEN fieldname = 'archiveID' THEN itemdatavalues.value END) AS 'archiveID',
  group_concat(CASE WHEN fieldname = 'presentationType' THEN itemdatavalues.value END) AS 'presentationType',
  group_concat(CASE WHEN fieldname = 'meetingName' THEN itemdatavalues.value END) AS 'meetingName',
  group_concat(CASE WHEN fieldname = 'programTitle' THEN itemdatavalues.value END) AS 'programTitle',
  group_concat(CASE WHEN fieldname = 'network' THEN itemdatavalues.value END) AS 'network',
  group_concat(CASE WHEN fieldname = 'reportNumber' THEN itemdatavalues.value END) AS 'reportNumber',
  group_concat(CASE WHEN fieldname = 'reportType' THEN itemdatavalues.value END) AS 'reportType',
  group_concat(CASE WHEN fieldname = 'institution' THEN itemdatavalues.value END) AS 'institution',
  group_concat(CASE WHEN fieldname = 'organization' THEN itemdatavalues.value END) AS 'organization',
  group_concat(CASE WHEN fieldname = 'nameOfAct' THEN itemdatavalues.value END) AS 'nameOfAct',
  group_concat(CASE WHEN fieldname = 'codeNumber' THEN itemdatavalues.value END) AS 'codeNumber',
  group_concat(CASE WHEN fieldname = 'publicLawNumber' THEN itemdatavalues.value END) AS 'publicLawNumber',
  group_concat(CASE WHEN fieldname = 'dateEnacted' THEN itemdatavalues.value END) AS 'dateEnacted',
  group_concat(CASE WHEN fieldname = 'thesisType' THEN itemdatavalues.value END) AS 'thesisType',
  group_concat(CASE WHEN fieldname = 'university' THEN itemdatavalues.value END) AS 'university',
  group_concat(CASE WHEN fieldname = 'studio' THEN itemdatavalues.value END) AS 'studio',
  group_concat(CASE WHEN fieldname = 'websiteTitle' THEN itemdatavalues.value END) AS 'websiteTitle'

FROM
  items
LEFT JOIN itemdata ON items.itemid = itemdata.itemid
LEFT JOIN fieldscombined ON itemdata.fieldid = fieldscombined.fieldid
LEFT JOIN itemdatavalues ON itemdata.valueid = itemdatavalues.valueid
GROUP BY items.itemid;

SELECT
  mainTable.*,
  json_group_array(CASE
    WHEN creators.firstName IS NOT NULL OR creators.lastName IS NOT NULL
      THEN json_object('f', creators.firstName, 'l', creators.lastName, 'm', creators.fieldMode)
  END) AS authors_json
FROM mainTable
LEFT JOIN itemCreators ON mainTable.itemID = itemCreators.itemID
LEFT JOIN creators ON itemCreators.creatorID = creators.creatorID
GROUP BY
  mainTable.itemID;
